sudo: "false"  # it is supposed to make builds faster

language: "node_js"
node_js:
  - "8"
  - "9"
  - "10"

# command to install dependencies
install:
  - "npm install"
  - "npm install -g codecov"
  - "npm install -g istanbul"

# command to run tests
script:
  - "npm test"

# Send everything to codecov
after_success:
  - "istanbul cover ./node_modules/mocha/bin/_mocha --report lcovonly -- -R spec && codecov"
