sudo: "false"  # it is supposed to make builds faster

language: "node_js"
node_js:
  - "8"
  - "9"
  - "10"

# command to install dependencies
install:
  - "npm install"

# command to run tests
script:
  - "npm test"

# Send everything to codecov
after_success:
  - "bash <(curl -s https://codecov.io/bash)"
