os: "linux"
dist: "bionic"

language: "node_js"
node_js:
    - "node"
    - "lts/*"

cache:
    npm: true

install:
  - "npm install"

script:
  - "npm test"

after_success:
  - "npm install -g codecov"
  - "codecov"
